name: dating
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.16
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  formz: ^0.6.0
  collection: ^1.17.2
  flutter_layout_grid: ^2.0.5
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  uuid: ^3.0.0
  flutter_image_compress: ^2.0.4
  timeago: ^3.5.0
  location: ^5.0.3
  hydrated_bloc: ^9.1.2
  photo_view: ^0.14.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  ionicons: ^0.2.2
  emoji_picker_flutter: ^1.6.1
  animations: ^2.0.8
  flutter_sim_country_code: ^0.1.2
  devicelocale: ^0.7.0
  phone_number: ^2.0.1
  android_sms_retriever: ^1.3.3
  flutter_appauth: ^6.0.2
  crypto: ^3.0.3
  onesignal_flutter: ^5.0.3
  image_picker_android: ^0.8.8+1
  image_picker_platform_interface: ^2.9.1
  image: ^4.1.3
  blurhash_dart: ^1.2.1
  blurhash: ^1.1.1
  image_size_getter: ^2.1.2
  flutter_isolate: ^2.0.4
  flutter_blurhash: ^0.7.0
  transparent_image: ^2.0.1
dev_dependencies:
  shared_preferences: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/flags2/
    - assets/icons/
    - assets/icons/custom/
    - assets/icons/circum/
    - assets/marmot.jpg
    - assets/images/
    - assets/emoji/noto/
    - assets/gifs/
    - assets/social/
  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
  generate: true